server:
  port: 7001
  servlet:
    context-path: /library #localhost:7001/library/books

spring:
  datasource:
    username: root
    password: 123root*
    url: jdbc:mysql://localhost:3306/PROD
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  jackson:
    serialization:
      fail-on-empty-beans: false
      